# LxWithPandas

In [1]:
import Lx

In [2]:
logFile='20171103__000001.log'

In [3]:
lx=Lx.LxSirOPC(logFile=logFile)

# pandas

In [4]:
import pandas as pd

In [5]:
lx.pdf.head()

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
0,1509725549039,INF,NMintRNB,Starting initialization...,None,None,None,None,None
1,1509725549040,DBG,NMintRNB,Logpath set: C:\3S\WDBochum_WV\Logs,None,None,None,None,None
2,1509725549040,DBG,NMintRNB,DB Object is null: False,None,None,None,None,None
3,1509725555520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO20413~KNO20211~~NSCH~id-43052790,1,,
4,1509725555520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO1136~KNO12708~~NSCH~id-4754434,1,,

In [6]:
# For object data (e.g. strings or timestamps), the result’s index will include count, unique, top, and freq. 
# The top is the most common value. The freq is the most common value’s frequency. 
# Timestamps also include the first and last items.
# for numeric data, the result’s index will include count, mean, std, min, max
lx.pdf.describe()

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
count,220908,182400,182400,182400,182347,182347,182347,182347,182347
unique,36812,5,8,17,8,16780,650,1,64754
top,ORA-08177: Zugriff fÃ¼r diese Transaktion kann...,STD,NMintRNB,<-,,,,,
freq,38498,117459,117543,117453,64894,64894,64894,182347,117453

In [7]:
lx.pdf[lx.pdf['#LogTime'].str.contains('^ORA')].describe()

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
count,38498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
top,ORA-08177: Zugriff fÃ¼r diese Transaktion kann...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,38498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Converting LogTime

In [8]:
lx.pdf['#LogTime'] = pd.to_datetime(lx.pdf['#LogTime'],unit='ms',errors='coerce') # NaT

In [9]:
lx.pdf.head(5)

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
0,2017-11-03 16:12:29.039,INF,NMintRNB,Starting initialization...,None,None,None,None,None
1,2017-11-03 16:12:29.040,DBG,NMintRNB,Logpath set: C:\3S\WDBochum_WV\Logs,None,None,None,None,None
2,2017-11-03 16:12:29.040,DBG,NMintRNB,DB Object is null: False,None,None,None,None,None
3,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO20413~KNO20211~~NSCH~id-43052790,1,,
4,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO1136~KNO12708~~NSCH~id-4754434,1,,

In [10]:
lx.pdf.sort_values(by='#LogTime',na_position='first').head(5)

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
55228,1970-01-01,None,None,None,None,None,None,None,None
59387,1970-01-01,None,None,None,None,None,None,None,None
59386,1970-01-01,None,None,None,None,None,None,None,None
59385,1970-01-01,None,None,None,None,None,None,None,None
59384,1970-01-01,None,None,None,None,None,None,None,None

In [11]:
lx.pdf.describe()

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
count,220908,182400,182400,182400,182347,182347,182347,182347,182347
unique,36802,5,8,17,8,16780,650,1,64754
top,1970-01-01 00:00:00,STD,NMintRNB,<-,,,,,
freq,38508,117459,117543,117453,64894,64894,64894,182347,117453
first,1970-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,2017-11-03 17:43:39.513000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
lx.pdf=lx.pdf.dropna()

In [13]:
lx.pdf.describe()

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
count,182347,182347,182347,182347,182347,182347,182347,182347,182347
unique,36781,5,8,2,8,16780,650,1,64754
top,2017-11-03 16:12:35.686000,STD,NMintRNB,<-,,,,,
freq,83,117453,117490,117453,64894,64894,64894,182347,117453
first,2017-11-03 16:12:35.520000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,2017-11-03 17:43:39.513000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
lx.pdf.head(5)

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
3,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO20413~KNO20211~~NSCH~id-43052790,1,,
4,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO1136~KNO12708~~NSCH~id-4754434,1,,
5,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO14100~KNO10027~~NSCH~id-4754720,1,,
6,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO12278~KNO12155~~NSCH~id-4754878,1,,
7,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO12958~KNO16516~~NSCH~id-4755066,1,,

In [15]:
lx.pdf.sort_values(by='#LogTime',na_position='first').head(5)

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
3,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO20413~KNO20211~~NSCH~id-43052790,1,,
24,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO9256~KNO9226~~NSCH~id-4757332,1,,
23,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO15050~KNO8549~~NSCH~id-4757356,1,,
22,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO26185~KNO2547~~NSCH~id-4756989,1,,
21,2017-11-03 16:12:35.520,STD,NMintRNB,<-,2017-11-03 16:12:22,ROHR~KNO82~KNO92~~NSCH~id-4757029,1,,

## Converting ProcessTime

In [16]:
lx.pdf['ProcessTime'] = pd.to_datetime(lx.pdf['ProcessTime'],errors='coerce') # NaT
lx.pdf.dtypes

#LogTime       datetime64[ns]
LogLevel               object
SubSystem              object
Direction              object
ProcessTime    datetime64[ns]
ID                     object
Value                  object
State                  object
Remark                 object
dtype: object

## Converting Value

In [17]:
lx.pdf.Value = lx.pdf.Value.str.replace(',', '.')

In [18]:
lx.pdf.Value=pd.to_numeric(lx.pdf.Value,errors='coerce') # NaN

## Excel

In [19]:
lx.pdf.to_excel('20171103__000001.xlsx', sheet_name='Sheet1')

In [20]:
df=lx.pdf[lx.pdf['ID'].str.contains('^TABL')]

# SIR 3S Processdata Import File

In [21]:
dfs=df.sort_values(by=['ID','ProcessTime','#LogTime'])

In [22]:
dfs['ID'].replace('(TABL~)(\S+)~~~SWVT', r'\2',regex=True,inplace=True)

In [23]:
dfs['LogDay'], dfs['LogTime'] = dfs['#LogTime'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]).str.split(' ',1).str

In [24]:
dfs['ProcessDay'], dfs['ProcessTime'] = dfs['ProcessTime'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]).str.split(' ',1).str

In [25]:
dfs.to_csv('20171103__000001_TABL.csv',sep=';',index=False,columns=['ID','ProcessDay','ProcessTime','Value'])