In [1]:
import logging

logFileName='Lx'

logger = logging.getLogger(logFileName)  

logFile= logFileName+'.log' 

loglevel = logging.DEBUG
logging.basicConfig(filename=logFile
                        ,filemode='w'
                        ,level=loglevel
                        ,format="%(asctime)s ; %(name)-60s ; %(levelname)-7s ; %(message)s")    

fileHandler = logging.FileHandler(logFile)     

logger.addHandler(fileHandler)

consoleHandler = logging.StreamHandler()
consoleHandler.setFormatter(logging.Formatter("%(levelname)-7s ; %(message)s"))
consoleHandler.setLevel(logging.INFO)
logger.addHandler(consoleHandler)

In [2]:
import pandas as pd
import time

In [3]:
import Lx
# from PT3S import Lx

## Initialisierung

In [4]:
zip7File=r'c:\Users\wolters\source\repos\PT3S\testdata\Lx\20201113_151238a - 6 Logs.7z'
logFile=r'c:\Users\wolters\source\repos\PT3S\testdata\Lx\20201113_0000003.log'

### mit Log

In [5]:
start = time.time()
lx=Lx.AppLog(logFile=logFile) # init with single log
end = time.time()
print(end - start)

9.578521966934204

### nochmal mit Log (wg. "Test" Detail restValues)

In [6]:
start = time.time()
lx=Lx.AppLog(logFile=logFile,parseRestvalues=True) # init with single log
end = time.time()
print(end - start)

33.7271294593811

### mit Zip (d.h. mit 1. Log in Zip)

In [7]:
start = time.time()
lx=Lx.AppLog(zip7File=zip7File) # init with 1st Log in zip
end = time.time()
print(end - start)

8.793988227844238

## mit Daten befuellen

### aus zip

In [8]:
start = time.time()
lx.addZip7File(zip7File) # data from zip
end = time.time()
dauer=end - start

In [9]:
print("6 logs benoetigen {!s:s} Sekunden".format(round(dauer,2)))
dauer400LogsinMinuten=round(dauer/6*400/60,2) # in einer Zip sind bei 1 GB ca. 400 Logs
print("400 logs benoetigen dann ca. {!s:s} Minuten".format(dauer400LogsinMinuten))
KalenderZeitProLogInMinuten=3.5 # Mittelwert
KalenderZeit400Logs=400*KalenderZeitProLogInMinuten
f=KalenderZeit400Logs/dauer400LogsinMinuten
print("Logs für 1 Kalendertag benoetigen dann in der Aufbereitung ca. {!s:s} Stunde(n)".format(round(24*60/f/60),2))

6 logs benoetigen 44.19 Sekunden
400 logs benoetigen dann ca. 49.1 Minuten
Logs für 1 Kalendertag benoetigen dann in der Aufbereitung ca. 1 Stunde(n)

In [10]:
lx.lookUpDf

                LogFile               FirstTime                LastTime
0  20201113_0000004.log 2020-11-13 14:24:54.973 2020-11-13 14:28:56.953
1  20201113_0000005.log 2020-11-13 14:28:56.952 2020-11-13 14:32:58.997
2  20201113_0000006.log 2020-11-13 14:32:58.995 2020-11-13 14:37:01.015
3  20201113_0000400.log 2020-11-14 16:30:34.386 2020-11-14 16:34:26.231
4  20201113_0000401.log 2020-11-14 16:34:26.229 2020-11-14 16:38:18.084
5  20201113_0000402.log 2020-11-14 16:38:18.083 2020-11-14 16:42:09.938

## Daten extrahieren

In [11]:
start = time.time()
df=lx.get() # data from zip - ohne Parameter alles; das ist i.d.R. viel zu viel fuer den Arbeitsspeicher
end = time.time()
dauer=end - start
print(dauer)

97.28437042236328

In [12]:
print("eine Kalenderzeit von {!s:s} Minuten benoetigt {!s:s} Minuten zum lesen".format(KalenderZeitProLogInMinuten*6,round(dauer/60,2)))
dauer/60/KalenderZeitProLogInMinuten*6
print("eine typische Analyse-Kalenderzeit von 30 Minuten benoetigt dann {!s:s} Minuten zum lesen".format(round(30*dauer/60/(KalenderZeitProLogInMinuten*6),2)))

eine Kalenderzeit von 21.0 Minuten benoetigt 1.62 Minuten zum lesen
eine typische Analyse-Kalenderzeit von 30 Minuten benoetigt dann 2.32 Minuten zum lesen

In [13]:
df.head()

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
0,2020-11-13 14:24:54.973,STD,LOGGING,nan,NaT,nan,NaN,nan,Logfilesize of /home/3sconsult/Logs/20201113_1...
1,2020-11-13 14:24:54.975,STD,LOGGING,nan,NaT,nan,NaN,nan,Free space in Log Directory: 195155144704
2,2020-11-13 14:24:55.000,INF,SQC,nan,NaT,nan,NaN,nan,Starting cycle for 2020-11-13 15:24:53.000
3,2020-11-13 14:24:55.000,INF,SQC,nan,NaT,nan,NaN,nan,Updating DFIDTs...
4,2020-11-13 14:24:55.027,STD,SQC,nan,NaT,nan,NaN,nan,Status is 0

In [14]:
df.tail()

,#LogTime,LogLevel,SubSystem,Direction,ProcessTime,ID,Value,State,Remark
1074743,2020-11-14 16:42:09.760,INF,OPC UA,->,2020-11-14 16:42:09.760,Objects.FBG_MESSW.4_SV1_10_FT_01.In.MW.value,302.740380,nan,Sensor: 1605372129098 Server: 1605372129098
1074744,2020-11-14 16:42:09.760,INF,OPC UA,->,2020-11-14 16:42:09.760,Objects.FBG_MESSW.6_BID_01_FT_01.In.MW.value,135.711097,nan,Sensor: 1605372128731 Server: 1605372128731
1074745,2020-11-14 16:42:09.760,INF,OPC UA,->,2020-11-14 16:42:09.760,Objects.FBG_MESSW.6_BID_10_FT_01.In.MW.value,394.957643,nan,Sensor: 1605372128934 Server: 1605372128934
1074746,2020-11-14 16:42:09.760,INF,OPC UA,->,2020-11-14 16:42:09.760,Objects.FBG_MESSW.6_SKV_10_PTI_01.In.MW.value,37.157869,nan,Sensor: 1605372129367 Server: 1605372129367
1074747,2020-11-14 16:42:09.938,STD,LOGGING,nan,NaT,nan,NaN,nan,Next Logfile: /home/3sconsult/Logs/20201113_15...

## Initialisierung mit H5

In [15]:
h5File=r'C:\Users\wolters\source\repos\PT3S\testdata\Lx\Log ab 2020 11 13 14 24 54.973000.h5'

In [16]:
start = time.time()
lx=Lx.AppLog(h5File=h5File) # init with H5 (init by "connection" to previuosly parsed Logs)
end = time.time()
print(end - start)

0.07285070419311523

In [17]:
lx.lookUpDf

                LogFile               FirstTime                LastTime
0  20201113_0000004.log 2020-11-13 14:24:54.973 2020-11-13 14:28:56.953
1  20201113_0000005.log 2020-11-13 14:28:56.952 2020-11-13 14:32:58.997
2  20201113_0000006.log 2020-11-13 14:32:58.995 2020-11-13 14:37:01.015
3  20201113_0000400.log 2020-11-14 16:30:34.386 2020-11-14 16:34:26.231
4  20201113_0000401.log 2020-11-14 16:34:26.229 2020-11-14 16:38:18.084
5  20201113_0000402.log 2020-11-14 16:38:18.083 2020-11-14 16:42:09.938